### ISSUE TITLE
Getting incomplete signature exception

### ISSUE THREAD

**Issue by sheetaljoshi** [awslabs/aws-sigv4-proxy#116]
Trying with host: *.vpc-lattice-svcs.us-west-2.on. and name vpc-lattice-svcs and I get error IncompleteSignatureException: Missing the 'x-amz-content-sha256' in canonical headers. Can you please help.

**Comment by alvinlin123** [comment]
I believe this is related to https://github.com/awslabs/aws-sigv4-proxy/pull/117?

**Comment by alvinlin123** [comment]
Also I think this is a duplicate issue of https://github.com/awslabs/aws-sigv4-proxy/issues/49, so I will close this one in favour of earlier issue.
