### ISSUE TITLE
Publish a package

### ISSUE THREAD

**Issue by jackivanov** [awslabs/aws-sigv4-proxy#18]
Hello,

Please publish a package to the GitHub registry for public usage.

Thanks!

**Comment by sboulkour** [comment]
With a release version :)

**Comment by k4r1** [comment]
FWIW it looks like they've published a docker image for this in a public ECR repo:
- `public.ecr.aws/aws-observability/aws-sigv4-proxy:1.0`

(Found [here](https://github.com/aws/eks-charts/blob/master/stable/aws-sigv4-proxy-admission-controller/values.yaml#L19))

**Comment by ranton256** [comment]
Thanks, @k4r1 , public.ecr.aws/aws-observability/aws-sigv4-proxy:1.0 is an official image setup for supporting using this proxy as documented in https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-existing-Prometheus.html which (one use case of this).

**Comment by alvinlin123** [comment]
As noted above, images are published to public.ecr.aws/aws-observability/aws-sigv4-proxy.
