### ISSUE TITLE
API Gateway calls return "unable to determine service"

### ISSUE THREAD

**Issue by Denish-M** [awslabs/aws-sigv4-proxy#29]
I followed instructions from README to call API Gateway execute-api endpoint.

```sh
curl -H 'Host: <rest-api-id>.execute-api.us-east-1.amazonaws.com' http://localhost:8080/stage/path
```

It prints following error:

```sh
unable to proxy request - unable to determine service from host: <rest-api-id>.execute-api.us-east-1.amazonaws.com
```

Further investigation suggested that function named `determineAWSServiceFromHost` in `handler/aws.go` fails to match host value because of dedicated API Gateway endpoint by resource.

**Comment by alvinlin123** [comment]
Hi @Denish-M

Can you try to use the `--name` flag to manually set the service name?

**Comment by Denish-M** [comment]
Thanks @alvinlin123 for suggestion.

I looked at the code and had to provide both `--name` and `--region` values. 

I have updated README with an example for docker run command with overrides: #31

**Comment by Denish-M** [comment]
Thanks @alvinlin123

I had to specify both
