### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by skwashd** [awslabs/aws-sigv4-proxy#47]
ARM64 is popping up more frequently including the M1 Macs. More AWS services are offering a Graviton2 option. 

Please provide an ARM64 build. I did a quick test and the proxy compiles ok for arm64.

**Comment by alvinlin123** [comment]
Starting from version 1.4, the image supports ARM 64. Please use public.ecr.aws/aws-observability/aws-sigv4-proxy:1.4

**Comment by skwashd** [comment]
Thanks for the update. Can you please tag releases in the repo?
