### ISSUE TITLE
Ability to support retries

### ISSUE THREAD

**Issue by sukrit007wawa** [awslabs/aws-sigv4-proxy#54]
**Issue**
We are injecting aws-sigv4-proxy for services like AMP to add sigv4 headers.  However, a lot of these services run into throttling issues and the client does not understand the "Throttling Exceptions" .  It would be nice to have retry mechanism support in aws-sigv4-proxy when we run into throttling issues.

**Comment by alvinlin123** [comment]
Hi, thank you for your suggestion. 

aws-sigv4-proxy is meant to be a very simply proxy that signs HTTP requests; hence, the retry logic should be the responsibility of the caller to aws-sigv4-proxy.
