### ISSUE TITLE
Feature request: provide a way to proxy requests into AWS Managed Prometheus instances

### ISSUE THREAD

**Issue by wattdave** [awslabs/aws-sigv4-proxy#66]
I am integrating an application that needs to make Prometheus queries, but doesn't (yet) have support for making AWS signed queries. It'd be great if this also had a mechanism to add a new host to be a target of the proxy.

**Comment by alvinlin123** [comment]
Hello, it is actually possible to call AWS Managed Prometheus through the proxy current. The [Using older versions of Prometheus doc](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-existing-Prometheus.html#AMP-onboard-ingest-metrics-existing-remotewrite) has an example. 

Essentially you can leverage the `--name` and `--host` parameter like the following: 

```
 go run cmd/aws-sigv4-proxy/main.go --region us-west-2 --name aps --host aps-workspaces.us-west-2.amazonaws.com
```
