### ISSUE TITLE
install the aws-sigv4-proxy on an EKS Cluster 

### ISSUE THREAD

**Issue by petereskandar** [awslabs/aws-sigv4-proxy#68]
Hi all,

there is a way to install the aws-sigv4-proxy on an EKS Cluster using ServiceAccounts instead of directly setting the IAM Role ?
all the examples provided show only how to install it using docker.

Thanks alot

**Comment by alvinlin123** [comment]
Hi, the Amazon Managed Service for Prometheus's documentation has an example of how to run the proxy in EKS/k8s

https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-existing-Prometheus.html#AMP-onboard-ingest-metrics-existing-remotewrite

Jump to the section "Using older versions of Prometheus".
